/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.failsafe.java-conventions")
}

dependencies {
    api(project(":failsafe"))
    api("com.squareup.retrofit2:retrofit:2.9.0")
    testImplementation(project(":failsafe"))
    testImplementation("com.google.code.gson:gson:2.9.0")
    testImplementation("com.squareup.retrofit2:converter-gson:2.3.0")
    testImplementation("com.github.tomakehurst:wiremock-jre8:2.32.0")
}

description = "Failsafe Retrofit"

java {
    withJavadocJar()
}
