/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.failsafe.java-conventions")
}

description = "Failsafe"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
