/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.failsafe.java-conventions")
}

dependencies {
    api(project(":failsafe"))
    api("com.squareup.okhttp3:okhttp:4.9.3")
    testImplementation(project(":failsafe"))
    testImplementation("com.github.tomakehurst:wiremock-jre8:2.32.0")
}

description = "Failsafe OkHttp"

java {
    withJavadocJar()
}
