/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "failsafe-parent"
include(":failsafe-okhttp")
include(":failsafe-retrofit")
include(":failsafe")
project(":failsafe-okhttp").projectDir = file("modules/okhttp")
project(":failsafe-retrofit").projectDir = file("modules/retrofit")
project(":failsafe").projectDir = file("core")
